version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app/public:/var/www/html/
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'fnc'
      MYSQL_PASSWORD: 'fnc'
      MYSQL_DATABASE: 'task'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "9903:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      restart: always

    ports:
      - "8081:80"
volumes:
  mysqldata: { }